import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

//getServerSideProps- runs only on server & before the component get  executed.
export async function getServerSideProps(){
  const {events_categories}=await import('../data/data.json')
  return {
    props:{
      data:events_categories
    }
  }
}

export default function Home({data}) {
  return (
    <>
    <header>
    <Head>
        <title>Event App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <img />
        <a href='/'>Home</a>
        <a href='/events'>Events</a>
        <a href='/about-us'>About Us</a>


      </nav>
    </header>
    
      <main className={styles.main}>
        <h1>All Events</h1>
        {data.map((data)=>{
          return (
            <>
                   <a key={data.id} href={`/events/${data.id}`}>
          <Image src={data.image} width={300} height={300} />
          <h2>{data.title}</h2>
          <p>{data.description}</p>
        </a>
    
            </>
          )
        })}
 
       
      </main>
      <footer className={styles.footer}>

      </footer>
    </>
  )
}

